default_dest: fcl-movies-20s:movies/20s
default_source: /zmedia/movies/20s
domains:
- admin_email: admin@flux-core-labs.com
  domain_name: flux-core-labs.com
  group_email: isyncusers@flux-core-labs.com
  remote_sa_json_path: /opt/sa/master-fcl.json
  sa_json_path: C:\Users\88\opt\isync\keys\master-fcl.json
existing_users_file: users.txt
global_rclone_flags: ''
max_users_per_cycle: 10
protected_users:
- admin@flux-core-labs.com
rclone_chunk_size: 128M
rclone_command: copy
rclone_stats_interval: 1s
rclone_verbose: true
rotation_strategy: standard
ssh_alias: ''
ssh_connect_timeout: 10
ssh_enabled: true
ssh_host: zfbak
ssh_key_path: ''
ssh_mode: explicit
ssh_remote_path: ~/isync
ssh_user: ''
stall_timeout_minutes: 10
step_check: false
transfers: 8
upload_limit: 750G
webhook_url: ''
