company_name: Internal Ops
default_dest: fcl-movies-20s:movies/20s
default_source: /zmedia/movies/20s
domains:
- admin_email: admin@flux-core-labs.com
  domain_name: flux-core-labs.com
  group_email: isyncusers@flux-core-labs.com
  remote_sa_json_path: /opt/sa/master-fcl.json
  sa_json_path: C:\Users\88\opt\isync\keys\master-fcl.json
- admin_email: master-sa@varlikkasa.com
  domain_name: varlikkasa.com
  group_email: dksa@varlikkasa.com
  remote_sa_json_path: /opt/sa/master-vk.json
  sa_json_path: C:\Users\88\opt\isync\keys\master-vk.json
- admin_email: admin@flux-core-command.com
  domain_name: flux-core-command.com
  group_email: isyncusers@flux-core-command.com
  remote_sa_json_path: /opt/sa/master-fcc.json
  sa_json_path: C:\Users\88\opt\isync\keys\master-fcc.json
- admin_email: admin@flux-core-grid.com
  domain_name: flux-core-grid.com
  group_email: isyncusers@flux-core-grid.com
  remote_sa_json_path: /opt/sa/master-fcg.json
  sa_json_path: C:\Users\88\opt\isync\keys\master-fcg.json
existing_users_file: users.txt
global_rclone_flags: --cutoff-mode=soft --no-update-dir-modtime --size-only --min-size=1G
include_protected_users: false
manual_ops:
  batch_dst: ''
  batch_src: ''
  create_delay: 10
  run_dst: ''
  run_src: ''
  target_user: ''
max_users_per_cycle: 1
protected_users:
- admin@flux-core-labs.com
- admin@flux-core-command.com
- admin@flux-core-grid.com
- master-sa@varlikkasa.com
rclone_chunk_size: 128M
rclone_command: copy
rclone_stats_interval: 10s
rclone_verbose: true
rotation_strategy: existing
ssh_alias: ''
ssh_connect_timeout: 10
ssh_enabled: true
ssh_host: zfbak
ssh_key_path: ''
ssh_mode: explicit
ssh_remote_path: ~/isync
ssh_user: ''
stall_timeout_minutes: 10
step_check: false
sync_pairs:
- dest: fcl-movies-20s:movies/20s
  domain_reference: flux-core-labs.com
  source: /zmedia/movies/20s
transfers: 16
upload_limit: 800G
webhook_url: ''
